### ISSUE TITLE
Please check if catalogNumba_irregular() is correct

### ISSUE THREAD

**Issue by danielbwright** [Ashar25/RainyDay#54]
I'm doing some speed testing and the changes to this function look strange. Specifically, it doesn't use the domainmask at all, so I don't know how it could handle non-rectangular domains.

**Comment by Ashar25** [comment]
I have changed the catalogNumba_irregular and it was really fast for me. I think I have discussed this changed with you. I am using domainmask before the function to get zeros where there is no domain in the rectangle. I am pretty sure the problem is with different libraries behaving differently with different versions.
